-- theme.lua — SNAPSHOT of ~/.config/omarchy/current/theme/hyprland.conf
-- Theme: Koyanagi | Snapshot date: 2026-09-08 | Hyprland 0.56.2 / Omarchy 3.8.2
--
-- ⚠️ READ THIS BEFORE EDITING:
-- The .conf theme file is REGENERATED by `omarchy theme set`. Lua cannot
-- source .conf files, so this is a frozen copy. After ANY `omarchy theme set`
-- (or theme update), re-snapshot: convert the new theme/hyprland.conf here
-- (same structure: locals → hl.config → hl.curve/animation → hl.layer_rule),
-- then `hyprctl reload` + `hyprctl configerrors`.
local background      = "rgba(262626ff)"
local surface         = "rgba(404040ff)"
local foreground      = "rgba(e6e6e6ff)"
local inactive_border = "rgba(404040ff)"
local shadow_color    = "rgba(00000066)"
local accent_white    = { colors = { "rgb(C0C0C0)", "rgb(D3D3D3)", "rgb(E5E5E5)", "rgb(B0B0B0)" } }
local accent_border   = "rgba(a7a7a7cc)"

hl.config({
    general = {
        gaps_in = 4,
        gaps_out = 6,
        border_size = 1,
        col = {
            active_border = accent_white,
            inactive_border = inactive_border,
        },
        resize_on_border = true,
        extend_border_grab_area = 15,
        allow_tearing = false,
        layout = "dwindle",
    },
})

hl.curve("snappy", { type = "bezier", points = { { 0.22, 1.0 }, { 0.35, 1.0 } } })
hl.curve("smooth", { type = "bezier", points = { { 0.23, 1.0 }, { 0.32, 1.0 } } })
hl.curve("slide", { type = "bezier", points = { { 0.165, 0.84 }, { 0.44, 1.0 } } })
hl.curve("overshot", { type = "bezier", points = { { 0.13, 0.99 }, { 0.29, 1.08 } } })
hl.curve("macspring", { type = "bezier", points = { { 0.18, 1.08 }, { 0.35, 1.06 } } })
hl.curve("md3_standard", { type = "bezier", points = { { 0.2, 0 }, { 0, 1 } } })
hl.curve("md3_accel", { type = "bezier", points = { { 0.3, 0 }, { 0.8, 0.15 } } })

hl.config({ animations = { enabled = true } })
hl.animation({ leaf = "windows", enabled = true, speed = 3, bezier = "snappy", style = "slide" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 4, bezier = "macspring", style = "popin 85%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 3, bezier = "snappy", style = "popin 85%" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 3, bezier = "snappy" })
hl.animation({ leaf = "fade", enabled = true, speed = 4, bezier = "smooth" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = 3, bezier = "smooth" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 2, bezier = "smooth" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 4, bezier = "slide" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 1.5, bezier = "overshot", style = "popin 80%" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 1.3, bezier = "md3_accel", style = "popin 90%" })
hl.animation({ leaf = "layers", enabled = true, speed = 1.5, bezier = "md3_standard" })
hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 3, bezier = "smooth" })
hl.animation({ leaf = "border", enabled = true, speed = 5, bezier = "smooth" })
hl.animation({ leaf = "borderangle", enabled = true, speed = 7, bezier = "smooth" })

hl.config({
    decoration = {
        rounding = 1,

        shadow = {
            enabled = true,
            range = 20,
            render_power = 10,
            color = accent_border,
            color_inactive = shadow_color,
            offset = "0 0",
        },

        blur = {
            enabled = true,
            size = 6,
            passes = 3,
            contrast = 1.5,
            brightness = 0.8,
            vibrancy = 0.2,
            vibrancy_darkness = 0.2,
            noise = 0.07,
            ignore_opacity = true,
            new_optimizations = true,
        },
        active_opacity = 0.98,
        inactive_opacity = 0.9,
        fullscreen_opacity = 1.0,
    },
})

-- gestures disabled: conflict with custom horizontal gesture in adibayu_input.conf
-- gestures {
--     gesture = 3, left, dispatcher, workspace, -1
--     gesture = 3, right, dispatcher, workspace, +1
-- }

hl.config({
    misc = {
        background_color = background,
    },
})

hl.layer_rule({ name = "theme-blur-walker", match = { namespace = "walker" }, blur = true, ignore_alpha = 0.2 })
hl.layer_rule({ name = "theme-blur-waybar", match = { namespace = "waybar" }, blur = true, ignore_alpha = 0.2 })
hl.layer_rule({ name = "theme-blur-notifications", match = { namespace = "notifications" }, blur = true, ignore_alpha = 0.2 })
hl.layer_rule({ name = "theme-blur-swayosd", match = { namespace = "swayosd" }, blur = true, ignore_alpha = 0.2 })
